### PR TITLE
ignore routing errors

### LINKED ISSUE #119: Catch routing exceptions sensibly
Used up the whole Rollbar quota this weekend by allowing 13,120 requests to `/phpmyadmin` to bubble all the way up and get sent. Requesting a route that doesn't exist should raise, then get caught and return a 404 instead.

### PR DESCRIPTION
**Pull request by camallen**
closes #119 - This PR avoid reporting UnknownRoute errors (404s) while still reporting other request errors to Rollbar as normal.

Based on https://github.com/slashdotdash/til/blob/master/elixir/rollbar-exception-reporting-for-phoenix.md#rollbar-exception-reporting-for-phoenix

### CODE REVIEW

File: web/router.ex [hunk 1]
```diff
@@ -26,14 +26,20 @@ defmodule Designator.Router do
     put "/users/:id/add_seen_subject", UserController, :add_seen_subject
   end
 
+  # Ignore Phoenix routing errors
+  defp handle_errors(_conn, %{reason: %Phoenix.Router.NoRouteError{}}), do: :ok
+
+  # report other request errors to rollbar
   defp handle_errors(conn, %{kind: kind, reason: reason, stack: stacktrace}) do
     Rollbax.report(kind, reason, stacktrace)
-    case Poison.encode(%{kind: kind, reason: reason}) do
```
Comment (yuenmichelle1) [inline web/router.ex:31]: Do we not need this part of code anymore?  with `send_resp`?

Comment (camallen) [reply web/router.ex:31]: Nope as we aren't manually sending a response anymore - now we are letting the system respond with "Server internal error" and json payload. 

Note that later in the comments I've switched to use the json responder https://hexdocs.pm/phoenix/1.2.5/Phoenix.Controller.html#json/2 vs the send_resp in the comments below. 

The `json` call encodes the data before sending the payload.

Comment (yuenmichelle1) [reply web/router.ex:31]: Ah got it got it 👍

**Review by yuenmichelle1 — APPROVED** [review]
